version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errname
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
  settings:
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (*github.com/kbrdn1/LazyCurl/internal/ui.EnvironmentsView).saveEnvironment
    goconst:
      min-len: 3
      min-occurrences: 7
      ignore-string-values:
        - tab
        - shift+tab
        - header
        - query
        - none
        - down
        - up
        - left
        - right
        - esc
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - hugeParam
        - evalOrder
        - emptyStringTest
        - rangeValCopy
        - appendCombine
        - assignOp
        - paramTypeCombine
        - typeAssertChain
        - singleCaseSwitch
        - unnamedResult
        - elseif
        - nestingReduce
        - builtinShadowDecl
        - dupBranchBody
        - equalFold
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-tags:
        - experimental
        - opinionated
    gocyclo:
      min-complexity: 100
    gosec:
      excludes:
        - G301
        - G304
        - G306
        - G404
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    misspell:
      locale: US
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: errorf
        - name: superfluous-else
        - name: unreachable-code
    staticcheck:
      checks:
        - all
        - -SA1019
        - -SA4006
        - -SA9003
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - gosec
        path: _test\.go
      - linters:
          - dupl
        path: .*\.gen\.go
      - linters:
          - dupl
          - errcheck
          - goconst
          - gocyclo
        path: internal/ui/.*_view\.go
      - linters:
          - goconst
          - gocyclo
        path: internal/ui/model\.go
      - linters:
          - dupl
          - errcheck
          - goconst
          - gocyclo
        path: internal/ui/components/
      - linters:
          - unparam
        path: internal/ui/
      - linters:
          - prealloc
        text: Consider pre-allocating
      - linters:
          - errcheck
        text: Error return value of `os.MkdirAll` is not checked
      - linters:
          - errcheck
        text: Error return value of `os.WriteFile` is not checked
      - linters:
          - errcheck
        text: Error return value of `e.saveEnvironment` is not checked
      - linters:
          - errcheck
        text: Error return value is not checked
      - linters:
          - revive
        path: internal/format/
        text: stutters
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kbrdn1/LazyCurl
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
