# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - dogsled
    - dupl
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    # - gochecknoinits  # Disabled - init() used for Go 1.20 compatibility
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    # - nilerr  # Disabled - Too many false positives in error handling patterns
    # - noctx  # Disabled - Context propagation requires significant refactoring
    # - nolintlint  # Disabled - Causes issues with nolint directives
    - prealloc
    - predeclared
    - revive
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow  # Disabled - shadow warnings are too strict for error handling patterns

  gocyclo:
    # Raised from 15 - TUI event handlers are inherently complex
    # Dialog.Update is at 66, RequestView.Update is at 91
    min-complexity: 100

  dupl:
    threshold: 150

  goconst:
    min-len: 3
    min-occurrences: 5
    # Ignore common UI strings
    ignore-strings: "tab|shift\\+tab|header|query|none"

  misspell:
    locale: US

  goimports:
    local-prefixes: github.com/kbrdn1/LazyCurl

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - hugeParam  # Bubble Tea uses value receivers for Update/View pattern
      - evalOrder  # False positives with defer-like patterns
      - emptyStringTest  # Style preference, not a bug
      - rangeValCopy  # Performance micro-optimization
      - appendCombine  # Style preference
      - assignOp  # Style preference
      - paramTypeCombine  # Style preference
      - typeAssertChain  # Common pattern in TUI code
      - singleCaseSwitch  # Sometimes clearer than if
      - unnamedResult  # Style preference

  exhaustive:
    # Don't require exhaustive switches for tea.KeyType (too many cases)
    default-signifies-exhaustive: true

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst

    # Exclude known issues in generated files
    - path: ".*\\.gen\\.go"
      linters:
        - dupl

    # UI view files have complex Update handlers - this is expected
    - path: internal/ui/.*_view\.go
      linters:
        - gocyclo
        - dupl
        - goconst

    # Model.go handles all app-level events - complexity is expected
    - path: internal/ui/model\.go
      linters:
        - gocyclo
        - goconst

    # UI components have complex event handlers
    - path: internal/ui/components/
      linters:
        - gocyclo
        - dupl
        - goconst

    # Unparam false positives for interface compliance
    - path: internal/ui/
      linters:
        - unparam

    # Prealloc is micro-optimization, not critical
    - linters:
        - prealloc
      text: "Consider pre-allocating"

    # errcheck exclusions for intentional error ignoring
    - path: internal/
      linters:
        - errcheck
      text: "Error return value of `os.MkdirAll` is not checked"

    - path: internal/
      linters:
        - errcheck
      text: "Error return value of `os.WriteFile` is not checked"

    # G404: math/rand is fine for non-crypto purposes (test data generation)
    - linters:
        - gosec
      text: "G404"

  max-issues-per-linter: 50
  max-same-issues: 10

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
