name: "Bug Report"
description: "Report a bug or unexpected behavior in LazyCurl"
title: "[Bug]: "
labels: ["fix"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out this form as completely as possible.

        Before submitting, please check the [existing issues](https://github.com/kbrdn1/LazyCurl/issues) to avoid duplicates.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open LazyCurl
        2. Navigate to '...'
        3. Press '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: A clear description of what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: A clear description of what actually happened...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality but workaround exists
        - High - Blocks major functionality
        - Critical - Application crashes or data loss
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Bug Category
      description: What area of LazyCurl is affected?
      options:
        - UI/UX
        - Collections Panel
        - Request Panel
        - Response Panel
        - Environments
        - HTTP Client
        - Configuration
        - Keybindings
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: LazyCurl Version
      description: What version of LazyCurl are you using?
      placeholder: "v0.1.0 or commit hash"
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go are you using? (run `go version`)
      placeholder: "go1.21.0"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: terminal
    attributes:
      label: Terminal
      description: What terminal emulator are you using?
      placeholder: "iTerm2, Alacritty, Windows Terminal, etc."
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Output
      description: If applicable, paste any error messages or logs
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help fix this bug?
      options:
        - label: I'm willing to submit a PR to fix this bug
          required: false
