name: "Feature Request"
description: "Suggest a new feature or enhancement for LazyCurl"
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out this form as completely as possible.

        Before submitting, please check the [existing issues](https://github.com/kbrdn1/LazyCurl/issues) to avoid duplicates.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this feature to work
      placeholder: A clear description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of LazyCurl does this feature relate to?
      options:
        - UI/UX
        - Collections
        - Environments
        - HTTP Client
        - Configuration
        - CLI/Commands
        - Authentication
        - Import/Export
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Essential for my use case
    validations:
      required: true

  - type: textarea
    id: mockup
    attributes:
      label: Mockup / Example
      description: If applicable, provide a mockup, diagram, or example of how this feature might work
      placeholder: |
        ```
        ┌─────────────────┬──────────────────┐
        │  Example UI     │   Layout         │
        └─────────────────┴──────────────────┘
        ```
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to submit a PR for this feature
          required: false
